Repository AY2425S2-CS2103T-T17-1/tp, pull requests merged in 2025-03, with the labels that each got.

#10 Add Wrongian photo
  docs/images/wrongian.png
Labels: type.Task, priority.High

#5 Add Lx's photo
  docs/images/clx3210.png
Labels: type.Task, priority.High

#7 Add details to AboutUs.md
  docs/AboutUs.md
Labels: type.Task, priority.High

#18 Add Xin Ni's photo
  docs/images/xinniyee.png
Labels: type.Task, priority.High

#14 Update readme to match project
  README.md
Labels: type.Task, priority.High

#19 Add AboutUs page (Xin Ni)
  docs/AboutUs.md
Labels: type.Task, priority.High

#11 Update AboutUs page (Wrongian)
  docs/AboutUs.md
Labels: type.Task, priority.High

#26 Update site-wide settings
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_config.yml
  docs/index.md
Labels: type.Task, priority.High

#29 Update AboutUs page to include Pranav
  docs/AboutUs.md
  docs/images/Pranav.jpg
Labels: type.Task, priority.High

#33 Add some use cases and minor changes
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#34 Update roles in about us page to be more consistent
  docs/AboutUs.md
Labels: type.Task, priority.High

#36 Updated Developer Guide for User stories, NFR, and Glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#40 Remove Pranav Photo JPG
  docs/images/Pranav.jpg
Labels: type.Bug, priority.Medium, severity.Low

#39 Add UI mockup
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#37 Add use cases to developer guide and do some final fixes
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#53 Feature - Command history (v1.2)
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/InputHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistoryMenu.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/controller/CommandHistoryActionHandler.java
  src/main/java/seedu/address/ui/controller/CommandHistoryMenuController.java
  src/main/resources/view/CommandHistoryMenu.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/InputHistoryTest.java
  src/test/java/seedu/address/ui/controller/CommandHistoryMenuControllerTest.java
Labels: type.Story, priority.High

#59 Fix - Update help command UG url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, severity.High

#65 Implement sort command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Story, priority.High

#74 Add viewnotes command
  src/main/java/seedu/address/logic/commands/ViewNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewNoteCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewNoteCommandParserTest.java
Labels: type.Story, priority.High

#73 Branch fuzzy search
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Enhancement, priority.High

#76 Release V1.3 Prep
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#78 Change build.gradle to have the name of our product
  build.gradle
Labels: type.Task, priority.High

#79 Change UI theme colours
  docs/images/Ui.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/theme.css
Labels: type.Enhancement, priority.Medium

#84 Fix output colour error
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, priority.High

#93 Docs: Add command history sequence diagrams
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandHistorySequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommandHistorySequenceDiagram.png
Labels: type.Task, priority.High

#95 Enable assertions in build.gradle file
  build.gradle
Labels: type.Task, priority.High

#90 Enhancement: Mass ops delete
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MassOpsIndexParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MassOpsIndexParserTest.java
Labels: type.Enhancement, priority.High

#98 Help for each command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: type.Enhancement, priority.High

#97 Feature - Add undo and redo commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: type.Story, priority.High

#102 Add Undo and Redo help command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, priority.High

#101 Change User Guide for Find and Help Command
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task, priority.High

#108 Update DG ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#120 DG: Update UI Components diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#125 Edit Command Summary for find and help command
  docs/UserGuide.md
Labels: type.Task, priority.High

#127 Update user guide for sort command, command summary, user interface, faq
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userinterface1.png
  docs/images/userinterface2.png
Labels: type.Task, priority.High

#110 Update user guide with undo, redo, viewnote, note commands
  docs/UserGuide.md
Labels: type.Task, priority.High

#124 Improve Undo/Redo Implementation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium, alpha-bug

#133 Fix - Update user guide
  docs/UserGuide.md
Labels: type.Bug, priority.High

#131 Add pin to ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#150 Fix Bugs in Help command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#163 Fix: Delete duplicate index
  src/main/java/seedu/address/commons/core/index/Index.java
  src/test/java/seedu/address/commons/core/index/IndexIntegrationTest.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/MassOpsIndexParserTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#165 Fix: Command history UI
  src/main/java/seedu/address/ui/CommandHistoryMenu.java
  src/main/resources/view/CommandHistoryMenu.css
Labels: type.Bug, severity.Medium, alpha-bug

#166 Fix: Sort removing Pin
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#175 Fix: Add pin icon
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.High, alpha-bug

#169 Fix: Consecutive duplicates and blank inputs in command history
  docs/UserGuide.md
  docs/images/commandHistory.png
  docs/images/emptyCommandHistory.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/InputHistory.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/InputHistoryTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#176 DG: Update Logic Delete sequence diagram
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: type.Task, priority.High

#178 Fix: Update FAQ
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#181 Nitpick: Fix long line of code
  src/main/java/seedu/address/logic/parser/MassOpsIndexParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.Low

#179 Fix Bugs and Enhance UG
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, type.Bug, priority.High, alpha-bug
