Repository AY2425S2-CS2103T-T17-1/tp, pull requests merged in 2025-04, with the labels that each got.

#180 Docs: Update user guide
  docs/UserGuide.md
  docs/images/commandHistoryOrder.png
Labels: type.Enhancement, priority.High

#185 Fix: Sort command bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FilteredPersonList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/FilteredPersonListTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#188 Bug Fix: Fix bug due to multiple nt/
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/descriptors/EditPersonDescriptor.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#189 Bug: Fix note usage message
  src/main/java/seedu/address/logic/commands/NoteCommand.java
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#186 UG: Update user guide
  docs/UserGuide.md
  docs/images/userinterface1.png
  docs/images/userinterface2.png
  docs/images/userinterface3.png
Labels: type.Bug, priority.High

#192 Fix duplicate person bug
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#193 Fix unable to undo certain commands
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/logic/commands/ViewNoteCommand.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#194 Fix: Tag names with spaces
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#203 Fix: Person details UI not updating as intended
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium, severity.Low, alpha-bug

#198 Fix: Change to input box
  docs/images/userinterface1.png
Labels: type.Bug, priority.Medium, severity.Low

#195 Fix: Error message for pinning/unpinning contact that is already pinned/not pinned
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/test/java/seedu/address/logic/commands/PinCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#214 Fix: Language of clear command in UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#215 Fix: Change wording to be more consistent in UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#217 Enhancement: Update UG with new command specifications
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#218 Enhancement: Clarify language of edit command to be more understandable
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#221 DG: Manual test and glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#212 Fix: Undo interaction with find
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/logic/commands/ViewNoteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModelState.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewNoteCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStateTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: type.Bug, priority.Medium, severity.High, alpha-bug

#222 Improvement: Change wording of features overview
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#209 Fix: Duplicate and null prefix for sort
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug, priority.High, severity.Medium

#207 DG: Implement sort, list, clear command and use cases
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/SortCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#226 Fix: Change from commitAddressBook to commit in DG
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/SortCommandSequenceDiagram.png
Labels: type.Bug, priority.High

#210 DG: Add delete and command history use cases, implementations and manual tests
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandHistorySequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/AddCommandHistorySequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommandHistorySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandHistoryMenu.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/CommandHistoryTest.java
  src/test/java/seedu/address/model/InputHistoryTest.java
Labels: type.Task, priority.High

#197 Add sequence diagram for edit
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
Labels: type.Task

#227 Enhancement: Improve code quality
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Note.java
Labels: type.Enhancement, priority.Medium

#234 Fix unclear assertions
  src/test/java/seedu/address/logic/commands/PinCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinCommandTest.java
Labels: type.Bug, priority.Low, severity.VeryLow, alpha-bug

#224 update DG for find and help
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/HelpCommandSequenceDiagram.puml
  docs/images/FindCommandSequenceDiagram.png
  docs/images/HelpCommandSequenceDiagram.png
Labels: type.Task, priority.High

#241 Fix: delete preamble allowing non blank strings
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, severity.Medium, alpha-bug

#245 Fix: Note unfilters list
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
Labels: type.Bug, priority.Medium, severity.VeryLow, alpha-bug

#247 Add Pin sequence diagram
  docs/diagrams/PinCommandSequenceDiagram.puml
  docs/images/PinCommandSequenceDiagram.png
Labels: type.Task

#248 Add Add command sequence diagram
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
Labels: type.Task

#243 Enhancement: Note and unredo/redo features in DG
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: type.Enhancement, priority.High

#231 Fix: Update ModelComponent section to be less outdated
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Bug, priority.Medium, severity.VeryLow

#305 Enhance Introduction segment of UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#317 Update index constraint in usage messages
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnpinCommand.java
  src/main/java/seedu/address/logic/commands/ViewNoteCommand.java
Labels: type.Bug, priority.High

#319 Fix email usage message
  src/main/java/seedu/address/model/person/Email.java
Labels: type.Bug, priority.Medium

#314 Allow duplicate names but not emails and add clear command in help window
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, type.Bug, priority.High

#322 Add GUI into glossary in UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#325 UG: Improve delete & command history docs
  docs/UserGuide.md
Labels: type.Task, priority.High

#326 Add planned enhancements section in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High

#327 Add warning about plantUML lifeline to multiple diagrams in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low, severity.Low

#321 Fix DG issues
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task, type.Bug, priority.High

#330 Improve UG command history and glossary
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#329 Fix issues related to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#315 Fix UI issues
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/pin.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, type.Bug, priority.High

#334 Update sample persons data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Task, priority.High

#338 Add design consideration for find
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#340 Remove isSameName method
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Task, priority.Medium

#341 Change message for duplicate person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Enhancement, priority.Medium

#333 DG: Update user stories & planned enhancements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#332 Make explanation for commands more visually appealing
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#328 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userinterface1.png
  docs/images/userinterface2.png
  docs/images/userinterface3.png
  docs/images/userinterface4.png
Labels: type.Task, type.Bug, priority.High

#345 Add design considerations for sort in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#357 UG: Add index issue to UG
  docs/UserGuide.md
Labels: type.Bug, priority.High

#351 DG: Update test case and planned enhancement sections
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#365 Fix planned enhancements formatting
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#356 Update note and viewnote sequence diagrams/manual testing/use cases in DG
  docs/DeveloperGuide.md
  docs/diagrams/NoteCommandSequenceDiagram.puml
  docs/diagrams/ViewNoteCommandSequenceDiagram.puml
  docs/images/NoteCommandSequenceDiagram.png
  docs/images/ViewNoteCommandSequenceDiagram.png
Labels: type.Enhancement, priority.Medium

#366 Update known issues with known bug on linux
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#367 Add planned enhancement for undo/redo
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#368 Add lifeline warning to note/viewnote sequence diagrams in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#369 Add index section in user guide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#372 Fix various issues in UG
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#373 Add another planned enhancement
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#339 Add feature specification for Edit and Pin into DG
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/PinCommandSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/PinCommandSequenceDiagram.png
  docs/images/PinSequenceDiagram.png
Labels: type.Task, priority.High

#370 DG: Add pin/unpin manual testing
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#376 Fix various DG/UG issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#350 Update hyperlinks in DG to correct links
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High

#377 Fix sort command in command summary
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low

#380 Add manual tests for add and edit commands
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#378 DG: Add Command implementation section
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
Labels: type.Enhancement, priority.High

#381 Update product scope in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#382 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium
